### ISSUE TITLE
“Last updated” on recently updated codelists is incorrect

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists-NonEmbedded#156]
E.g. http://iatistandard.org/202/codelists/Sector/ says:

> _Last updated on 2016-08-03_

…but I can see the new updates there from this week.

[The SSOT README](https://github.com/IATI/IATI-Standard-SSOT/blob/version-2.02/README.rst#building-a-website-that-also-includes-additonal-guidance) seems to suggest the problem might be the git repo in the `docs` directory:

> The `docs` directory should be a git repository in order to support adding the "Last updated" line to the bottom of the page. We build the live and dev websites in different directories so that the last updated date corresponds to when the site was actually changed, not when the relevant commit was added to the source git respository.

Btw it’s possible this issue should be against a different repo. Feel free to move it!

**Comment by hayfield** [comment]
This is something to do with the magic involved in the website generation process, with dates being brought in from a range of different locations, combined, smushed and something being output at the end of the process.

The upcoming work on the website will make the page generation process more streamlined and prevent situations like this from occurring. It will also allow for this sort of information to be displayed on a wider range of pages. As such, this won't be fixed with the current website architecture (though could be removed so as to prevent incorrect information from being displayed?).

**Comment by andylolz** [comment]
> (though could be removed so as to prevent incorrect information from being displayed?).

If it’s not going to be fixed (with the current website architecture), then I am definitely in favour of removing it.

**Comment by andylolz** [comment]
@hayfield thanks for your reply on this.

> (though could be removed so as to prevent incorrect information from being displayed?).

If it’s not going to be fixed (with the current website architecture), then I am definitely in favour of removing it.

> This is something to do with the magic involved in the website generation process, with dates being brought in from a range of different locations, combined, smushed and something being output at the end of the process.

It looks like this is the bit that does it:
https://github.com/IATI/IATI-Standard-SSOT/blob/695c8456045f80eefd2bc4d8ac02f7972e3dc068/combined_gen.sh#L23-L25

I.e. it’s relatively straightforward. But perhaps the git repository in /docs on the build server is broken in some way?

**Comment by hayfield** [comment]
It's been agreed that this will be removed from the website at the moment, and re-assesed as a potential feature with the updated website architecture.

This is due to a combination of:

* Dates flat out do not appear on some pages
* Incorrect dates appear on various pages where there are dates
* Where they are correct, the age of the dates doesn't provide much information beyond "this hasn't been updated in a while"
* There are separate changelogs for when key information changes, providing more information that just the date

> But perhaps the git repository in /docs on the build server is broken in some way?

There are several parts of the generation process that *just work* and modifying them is a somewhat risky business (there are limited tests, and reverting even the simplest of changes can be... not entirely straightforward).
