### ISSUE TITLE
IndicatorVocabulary: Add Code

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Codelists-NonEmbedded#180]
Make the following changes to the IndicatorVocabulary Codelist:

**Add Code:**

- [ ] Code: `8`
  - [ ] Name: `UN Sustainable Development Goals (SDG) Indicators`
  - [ ] URL: `http://unstats.un.org/unsd/statcom/47th-session/documents/2016-2-IAEG-SDGs-Rev1-E.pdf`

**Comment by hayfield** [comment]
There is already a code `8` on this Codelist.

**Comment by PetyaKangalova** [comment]
While this was added as a 2.03 upgrade proposal, the only change required was to update the link- see in [here.](https://discuss.iatistandard.org/t/results-add-more-indicator-vocabularies-excluded-2-03/870/9).  As indicator vocabulary is a non-embedded codelist, no changes are required now- see[ this comment.](https://discuss.iatistandard.org/t/results-add-more-indicator-vocabularies-excluded-2-03/870/12).

Overall, all SDG Indicator Vocabulary codes have been added so this issue is no longer relevant and should be closed.

**Comment by hayfield** [comment]
This change will not occur.
