### ISSUE TITLE
AidTypeVocabulary: Add Codes

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Codelists-NonEmbedded#185]
**Note:** This Codelist does not yet exist. There is a separate issue (#183) for that.

**Codes to add:**
- [x] Code `1`
  - [x] Name: `OECD DAC`
- [x] Code `2`
  - [x] Name: `OCHA`

**Codes to remove (added in #188)**

- [x] Code `2`
  - [x] Name: `OCHA`

**Comment by hayfield** [comment]
There are queries about what the `OCHA` Codelist refers to.

@wendyrogers may be able to advise.

**Comment by allthatilk** [comment]
@IATI/bas can we get an update on this? =)

**Comment by allthatilk** [comment]
Added changes according to current state but will make note in PR that it's subject to change.

**Comment by PetyaKangalova** [comment]
Please proceed with adding **only** Code 1- OECD DAC and **not** Code 2- OCHA.

The reason for this is that Code 2- OCHA was provisionally added during the 2.03 upgrade consultation. However, there is no external link to an OCHA codelist. @wendyrogers and I have been working in developing two additional AidTypeVocabulary codes that can be put forward through the non-embedded codelist process (earmarking category and earmarking modality) in early January at the latest.

**Comment by amy-silcock** [comment]
Changes can be seen here: http://reference.iatistandard.org/203/codelists/AidTypeVocabulary/

**Comment by andylolz** [comment]
I think the URL for code 1 should point to:
http://reference.iatistandard.org/codelists/AidType/

…rather than:
http://www.oecd.org/dac/stats/dacandcrscodelists.htm

That would be more consistent with code 2 (Earmarking Category).

It would be less consistent with [Sector Vocabulary](http://reference.iatistandard.org/codelists/SectorVocabulary/), which points to OECD. But again, I think that would be clearer if it pointed to the IATI copies.
