### ISSUE TITLE
Codelist management rules (on adding `status`, `activation-date` and `withdrawal-date`) are almost never followed

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists-NonEmbedded#244]
On the [IATI Codelist Management](http://iatistandard.org/203/codelists/codelist-management/) page, the section “[Code status, addition and withdrawal dates](http://iatistandard.org/203/codelists/codelist-management/#code-status-addition-and-withdrawal-dates)” says:

> All new codes added to codelist from the release of version 2.02 (December 2015) will feature `status="active"` and `activation-date` attributes in the underlying GitHub source code repositories. Similarly, codes withdrawn from the release of version 2.02 (December 2015) will feature `status="withdrawn"` and `withdrawal-date` attributes.

However, this doesn’t seem to be followed. I’ve sometimes done it for DAC codelist additions, but I’m not sure there are any other occurrences.

**Comment by rolfkleef** [comment]
The discussion in #278 was about what date should be used (in the case of non-embedded codelists).

It could be the date of the change in the source list, or the date of the change in the IATI list.

The [discussion about adding these attributes](https://support.iatistandard.org/hc/en-us/articles/214390846) and the documentation itself appears to leave room for multiple interpretations.

For me both issues go back to defining the actual use case for this.

It makes sense to know since when a code is no longer in use, but the choice of date is up for debate: do we consider the original source as authoritative or can I use the IATI website as authoritative source for what I code I can use today? In the latter case, the activation or withdrawal date should be the data of the IATI list change.
