### ISSUE TITLE
Pull DAC codes from source programattically

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists-NonEmbedded#52]
This should keep withdrawn codes on the list, see the approach for other codelists at https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/51

Except where stated, these are taken orginally from the spreadsheet linked at http://www.oecd.org/dac/stats/dacandcrscodelists.htm

These are now also available as XML, but there are still concerns about the XML/spreadsheet not matching. Historic data also doesn't seem to be available in a machine readable format.
- [ ] [AidType](http://iatistandard.org/codelists/AidType/)
- [ ] [CollaborationType](http://iatistandard.org/codelists/CollaborationType/)
- [ ] [FinanceType](http://iatistandard.org/codelists/FinanceType/)
- [ ] [PolicySignificance](http://iatistandard.org/codelists/PolicySignificance/) - https://github.com/IATI/IATI-Codelists-NonEmbedded/blob/master/xml/PolicySignificance.xml
- [ ] [FlowType](http://iatistandard.org/codelists/FlowType/)
- [ ] [Region](http://iatistandard.org/codelists/Region/)
- [ ] [Sector](http://iatistandard.org/codelists/Sector/)
- [ ] [SectoryCategory](http://iatistandard.org/codelists/SectorCategory/)

**Comment by andylolz** [comment]
In the short term, at least, this could use:
https://andylolz.github.io/dac-crs-codes/

**Comment by amy-silcock** [comment]
This does not fit with current plans to keep IATI/DAC codelists in sync.

**Comment by samuele-mattiuzzo** [comment]
Hi @andylolz , we're currently going through various repositories to do some cleanup; this issue will not be discarded, it just does not fit in this quarter's pipeline so we're closing it for now. Once we'll tackle it, we'll make sure this is re-created.

**Comment by andylolz** [comment]
Hi @samuele-mattiuzzo – the idiomatic approach would be to label this with “on hold” or similar, rather than closing. Closing is usually reserved for when an issue is fixed, or won’t be fixed.

By the sounds of it, there’s no intention to address this during this quarter. That’s fine, but In that case, do you mind if I bump [this post](https://discuss.iatistandard.org/t/january-2018-dac-codelist-updates/1297/7) again to ask that the pull request to update DAC codelists is reviewed and merged, as a stopgap until the more sustainable solution can be completed? Bill said this work was “in the job queue” but if it’s not scheduled for the current quarter, then recent changes should be merged another way. Some of the updates in that PR are from January 2018. Fortunately, they’re all very minor, so it should be trivial to review and merge them.

Longer term, if the plan is to pull DAC codes programmatically from DAC XML (I’m not 100% clear whether that’s actually the plan?) then I’d be happy to send a pull request for that.
